# Generated by Django 5.2.3 on 2025-06-18 16:56

import django.db.models.deletion
import filer.fields.image
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("djangocms_blog", "0001_squashed_0051_alter_blogconfig_type_and_more"),
        ("filer", "0017_image__transparent"),
        ("sites", "0002_alter_domain_unique"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="authorentriesplugin",
            name="authors",
            field=models.ManyToManyField(related_name="+", to=settings.AUTH_USER_MODEL, verbose_name="authors"),
        ),
        migrations.AlterField(
            model_name="blogcategory",
            name="main_image",
            field=filer.fields.image.FilerImageField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.FILER_IMAGE_MODEL,
                verbose_name="main image",
            ),
        ),
        migrations.AlterField(
            model_name="blogcategory",
            name="main_image_full",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="filer.thumbnailoption",
                verbose_name="main image full",
            ),
        ),
        migrations.AlterField(
            model_name="blogcategory",
            name="main_image_thumbnail",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="filer.thumbnailoption",
                verbose_name="main image thumbnail",
            ),
        ),
        migrations.AlterField(
            model_name="blogconfig",
            name="default_image_full",
            field=models.ForeignKey(
                blank=True,
                help_text="If left empty the image size will have to be set for every newly created post.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="filer.thumbnailoption",
                verbose_name="default size of full images",
            ),
        ),
        migrations.AlterField(
            model_name="blogconfig",
            name="default_image_thumbnail",
            field=models.ForeignKey(
                blank=True,
                help_text="If left empty the thumbnail image size will have to be set for every newly created post.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="filer.thumbnailoption",
                verbose_name="default size of thumbnail images",
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="sites",
            field=models.ManyToManyField(
                blank=True,
                help_text="Select sites in which to show the post. If none is set it will be visible in all the configured sites.",
                related_name="djangocms_blog_posts",
                to="sites.site",
                verbose_name="Site(s)",
            ),
        ),
        migrations.AlterField(
            model_name="postcontent",
            name="id",
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
        ),
    ]
