# Generated by Django 5.2.3 on 2025-06-24 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangocms_stories', '0002_auto_20250618_1556'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'get_latest_by': 'date_published', 'ordering': ('-date_published', '-date_created'), 'verbose_name': 'post', 'verbose_name_plural': 'posts'},
        ),
        migrations.AlterModelOptions(
            name='postcontent',
            options={'get_latest_by': 'date_published', 'ordering': ('-post__date_published', '-post__date_created'), 'verbose_name': 'post content', 'verbose_name_plural': 'post contents'},
        ),
        migrations.RemoveField(
            model_name='post',
            name='enable_liveblog',
        ),
        migrations.RemoveField(
            model_name='post',
            name='pinned',
        ),
        migrations.RemoveField(
            model_name='post',
            name='publish',
        ),
    ]
