name: migration test

on: [pull_request]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  migrate-project:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        requirements: [
          'dj52_cms41.txt',
        ]
        python-version: ['3.13']
        os: [
          ubuntu-latest,
        ]

    steps:
    - uses: actions/checkout@v4
    - name: Install system dependencies
      run: sudo apt update && sudo apt install -y libcairo2-dev
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip uv
        uv pip install --system -r ./tests/requirements/${{ matrix.requirements }}
        uv pip install --system aldryn-apphooks-config
    - name: Create djangocms-blog setup
      run: |
        python tests/test_migrations/run_migration_tests.py --phase1
    - name: Test migration from djangocms-blog to djangocms-stories
      run: |
        python tests/test_migrations/run_migration_tests.py --phase2
